version: '3.8'

services:
  migrate:
    build:
      context: .
      target: development
    image: hedera-mcp-server:migrate
    container_name: hedera-mcp-migrate
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite://./data/credits.db}
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./docker/run-migrations.sh:/app/run-migrations.sh:ro
    command: ["/app/run-migrations.sh"]
    depends_on:
      postgres:
        condition: service_healthy
        required: false