version: '3.8'

# Development Docker Compose - Optimized for local development
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: hedera-mcp:dev
    container_name: hedera-dev
    ports:
      - "3000:3000"      # MCP Server
      - "3001:3001"      # Admin Portal  
      - "3002:3002"      # HTTP API
      - "9229:9229"      # Node.js debugger
    environment:
      # Development settings
      NODE_ENV: development
      LOG_LEVEL: debug
      
      # Hedera Configuration
      HEDERA_NETWORK: ${HEDERA_NETWORK:-testnet}
      HEDERA_OPERATOR_ID: ${HEDERA_OPERATOR_ID}
      HEDERA_OPERATOR_KEY: ${HEDERA_OPERATOR_KEY}
      SERVER_ACCOUNT_ID: ${SERVER_ACCOUNT_ID}
      SERVER_PRIVATE_KEY: ${SERVER_PRIVATE_KEY}
      
      # Database (SQLite for dev)
      DATABASE_URL: sqlite:///app/data/credits.db
      
      # Credits
      CREDITS_CONVERSION_RATE: 1000
      
      # API Keys
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      API_KEY_ENCRYPTION_KEY: ${API_KEY_ENCRYPTION_KEY:-dev-encryption-key}
      
      # Admin Portal
      NEXT_PUBLIC_HEDERA_NETWORK: ${HEDERA_NETWORK:-testnet}
      NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${WALLETCONNECT_PROJECT_ID}
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3002
      NEXT_PUBLIC_APP_URL: http://localhost:3001
      
      # Development features
      FORCE_COLOR: 1
      DEBUG: ${DEBUG:-*}
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:delegated
      - ./admin-portal/app:/app/admin-portal/app:delegated
      - ./admin-portal/components:/app/admin-portal/components:delegated
      - ./admin-portal/lib:/app/admin-portal/lib:delegated
      - ./admin-portal/public:/app/admin-portal/public:delegated
      - ./package.json:/app/package.json:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
      - ./drizzle.config.ts:/app/drizzle.config.ts:delegated
      - ./.env:/app/.env:delegated
      
      # Persist data
      - dev_data:/app/data
      - dev_logs:/app/logs
      
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/admin-portal/node_modules
      - /app/admin-portal/.next
    stdin_open: true
    tty: true
    networks:
      - dev-network

  # Optional: PostgreSQL for development
  postgres:
    image: postgres:16-alpine
    container_name: hedera-postgres-dev
    environment:
      POSTGRES_DB: hedera_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev-network
    profiles:
      - with-postgres

  # Optional: Redis for development
  redis:
    image: redis:7-alpine
    container_name: hedera-redis-dev
    ports:
      - "6379:6379"
    networks:
      - dev-network
    profiles:
      - with-redis

volumes:
  dev_data:
    driver: local
  dev_logs:
    driver: local
  postgres_dev_data:
    driver: local

networks:
  dev-network:
    driver: bridge