version: '3.8'

# PostgreSQL override configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.postgres.yml up

services:
  app:
    environment:
      # Override DATABASE_URL to use PostgreSQL
      DATABASE_URL: postgresql://${POSTGRES_USER:-hedera}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-hedera_mcp}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: hedera-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hedera_mcp}
      POSTGRES_USER: ${POSTGRES_USER:-hedera}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - hedera-network

volumes:
  postgres_data:
    driver: local