# Standalone deployment - MCP Server only with external database
# This is the recommended production deployment approach
version: '3.8'

services:
  mcp-server:
    build:
      context: .
      target: production
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: hedera-mcp-server:latest
    container_name: hedera-mcp-server
    ports:
      - "${MCP_PORT:-3000}:3000"  # MCP server
      - "${API_PORT:-3002}:3002"    # HTTP API
    environment:
      # Core Configuration
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Database - Use external service (required)
      # Examples:
      # - SQLite: sqlite:///app/data/credits.db
      # - Supabase: postgresql://postgres:[YOUR-PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres
      # - Neon: postgresql://user:password@ep-cool-darkness-123456.us-east-2.aws.neon.tech/dbname
      - DATABASE_URL=${DATABASE_URL}
      
      # Hedera Configuration (required)
      - HEDERA_NETWORK=${HEDERA_NETWORK}
      - HEDERA_OPERATOR_ID=${HEDERA_OPERATOR_ID}
      - HEDERA_OPERATOR_KEY=${HEDERA_OPERATOR_KEY}
      - SERVER_ACCOUNT_ID=${SERVER_ACCOUNT_ID}
      - SERVER_PRIVATE_KEY=${SERVER_PRIVATE_KEY}
      
      # Credits Configuration
      - CREDITS_CONVERSION_RATE=${CREDITS_CONVERSION_RATE:-1000}
      - CREDITS_MINIMUM_PAYMENT=${CREDITS_MINIMUM_PAYMENT:-1}
      - CREDITS_MAXIMUM_PAYMENT=${CREDITS_MAXIMUM_PAYMENT:-10000}
      
      # Performance & Security
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - ENABLE_METRICS=${ENABLE_METRICS:-true}
      
      # Optional: Redis cache (if using external Redis)
      - REDIS_URL=${REDIS_URL}
      
      # Required for conversational agent
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Admin portal CORS
      - ADMIN_PORTAL_URL=${ADMIN_PORTAL_URL:-http://localhost:3001}
    volumes:
      # Only needed for SQLite
      - mcp_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: ${MCP_MEMORY_LIMIT:-512M}
          cpus: '${MCP_CPU_LIMIT:-0.5}'
        reservations:
          memory: ${MCP_MEMORY_RESERVATION:-256M}
          cpus: '${MCP_CPU_RESERVATION:-0.25}'

volumes:
  mcp_data:
    driver: local