version: '3.8'

# Redis override configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.redis.yml up

services:
  app:
    environment:
      # Redis is automatically used when REDIS_URL is set
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: hedera-redis
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - hedera-network

volumes:
  redis_data:
    driver: local